name: build

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Macaron
        uses: actions/checkout@v4
        with:
          repository: oracle/macaron
          ref: 'staging'
          path: macaron

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test path
        run: cat macaron/docker/Dockerfile.final

      - name: Download Macaron wheel
        run: |
          curl -fLo macaron/dist/macaron-0.4.0-py3-none-any.whl --create-dirs https://github.com/oracle/macaron/releases/download/v0.4.0/macaron-0.4.0-py3-none-any.whl

      - name: Test wheel content
        run: unzip -l macaron/dist/macaron*.whl

      - name: Log in to GitHub Container Registry
        run: >
          docker login ghcr.io
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build Macaron image
        uses: docker/build-push-action@v4
        with:
          context: macaron/
          file: macaron/docker/Dockerfile.final
          build-args:
            WHEEL_PATH=dist/macaron-0.4.0-py3-none-any.whl
          tags: ghcr.io/nathanwn/macaron:latest
          platforms: linux/amd64,linux/arm64
          push: true
