name: build

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # This is required to push the images to ghcr.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Macaron
        uses: actions/checkout@v4
        with:
          repository: oracle/macaron
          ref: 'staging'
          path: '.'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: aarch64
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"
          CIBW_BEFORE_BUILD: >
            yum install make curl wget unzip -y &&
            curl -so "/tmp/go1.21.7.linux-arm64.tar.gz" -L "https://go.dev/dl/go1.21.7.linux-arm64.tar.gz" &&
            rm -rf /usr/local/go &&
            tar -C /usr/local -xzf /tmp/go1.21.7.linux-arm64.tar.gz &&
            export PATH=$PATH:/usr/local/go/bin &&
            go version &&
            which python3.11 &&
            python3.11 -m venv .venv &&
            source .venv/bin/activate &&
            make setup

      - name: Check built wheels
        run: ls -la ./wheelhouse/*.whl

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
      #     path: ./wheelhouse/*.whl

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Test path
      #   run: cat macaron/docker/Dockerfile.final

      # - name: Download Macaron wheel
      #   run: |
      #     curl -fLo macaron/dist/macaron-0.4.0-py3-none-any.whl --create-dirs https://github.com/oracle/macaron/releases/download/v0.4.0/macaron-0.4.0-py3-none-any.whl

      - name: Test wheel content
        run: unzip -l ./wheelhouse/macaron*.whl
        # run: unzip -l macaron/dist/macaron*.whl

      # - name: Log in to GitHub Container Registry
      #   run: >
      #     docker login ghcr.io
      #     --username ${{ github.actor }}
      #     --password ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Macaron image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: macaron/
      #     file: macaron/docker/Dockerfile.final
      #     build-args:
      #       WHEEL_PATH=dist/macaron-0.4.0-py3-none-any.whl
      #     tags: ghcr.io/nathanwn/macaron:latest
      #     platforms: linux/amd64,linux/arm64
      #     push: true
